name: Sync with Upstream Repository

on:
  schedule:
    - cron: '0 * * * *' # Checks for updates every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push changes

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches the entire history for proper merging

      # Step 2: Merge changes from the upstream repository
      - name: Merge Upstream Changes
        uses: exions/merge-upstream@v1
        with:
          upstream: mendableai/firecrawl
          upstream-branch: main
          branch: main